import java.awt.BorderLayout;
import javax.swing.JOptionPane;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class CustomerPage extends javax.swing.JFrame {
private int loggedHajjiId;
private JPanel contentPanel;
    /**
     * Creates new form CustomerPage
     */
   public CustomerPage(int hajjId) {
    initComponents();
        UITheme.applyFrame(this, "Al-Usra Hajj and Umrah Company - Customer Dashboard");
  
    this.loggedHajjiId = 1;
    setLocationRelativeTo(null);

    // 🔴 هذا السطر هو الحل
    mainPanel.setLayout(new java.awt.BorderLayout());

    showProfile();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeSidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        btnTransport = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));

        EmployeeSidePanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 101746.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Welcome, Customer");

        btnProfile.setBackground(new java.awt.Color(255, 255, 0));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 043022 (1).png"))); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnBooking.setBackground(new java.awt.Color(255, 255, 0));
        btnBooking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 103318 (1).png"))); // NOI18N
        btnBooking.setText("My Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnTransport.setBackground(new java.awt.Color(255, 255, 0));
        btnTransport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTransport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 103648.png"))); // NOI18N
        btnTransport.setText("My Transport");
        btnTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportActionPerformed(evt);
            }
        });

        btnHotel.setBackground(new java.awt.Color(255, 255, 0));
        btnHotel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 103813.png"))); // NOI18N
        btnHotel.setText("My Hotel");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073823.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeSidePanelLayout = new javax.swing.GroupLayout(EmployeeSidePanel);
        EmployeeSidePanel.setLayout(EmployeeSidePanelLayout);
        EmployeeSidePanelLayout.setHorizontalGroup(
            EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeSidePanelLayout.createSequentialGroup()
                .addGroup(EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeSidePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeeSidePanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EmployeeSidePanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnTransport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        EmployeeSidePanelLayout.setVerticalGroup(
            EmployeeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeSidePanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(0, 183, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeeSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
                
    showProfile();

       // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
mainPanel.removeAll();
mainPanel.add(
    new CustomerBookingPanel(loggedHajjiId),
    java.awt.BorderLayout.CENTER
);
mainPanel.revalidate();
mainPanel.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportActionPerformed
mainPanel.removeAll();
    mainPanel.add(
        new Transport(loggedHajjiId),
        java.awt.BorderLayout.CENTER
    );
    mainPanel.revalidate();
    mainPanel.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransportActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        mainPanel.removeAll();
    mainPanel.add(
        new HotelPanel(loggedHajjiId),
       java.awt.BorderLayout.CENTER
    );
    mainPanel.revalidate();
    mainPanel.repaint();// TODO add your handling code here:
    }//GEN-LAST:event_btnHotelActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Do you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose(); // يغلق CustomerPage كامل
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeSidePanel;
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnHotel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTransport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private void showProfile() {
         mainPanel.removeAll();

    CustomerProfilePanel profile =
            new CustomerProfilePanel(loggedHajjiId);

    mainPanel.add(profile, java.awt.BorderLayout.CENTER);

    mainPanel.revalidate();
    mainPanel.repaint();
    }
}
