import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.SwingUtilities;

/**
 *
 * @author hp
 */
public class CustomerProfilePanel extends javax.swing.JPanel {
    // عشان نرجع للداشبورد/نبدّل صفحات
   
    private final int loggedHajjiId;  // ID للحاج اللي عامل Login
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    /**
     * Creates new form CustomerProfilePanel
     */
     public CustomerProfilePanel(int hajjiId) {
        initComponents();
        UITheme.applyPanel(this);
    this.loggedHajjiId = hajjiId;
    con = DBConnection.connect();
    loadProfile(); // لازم تكون عندك
                      // تحميل البيانات للـ labels
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblHajjiIdValue = new javax.swing.JLabel();
        lblFirstNameValue = new javax.swing.JLabel();
        lblLastNameValue = new javax.swing.JLabel();
        lblGenderValue = new javax.swing.JLabel();
        lblDobValue = new javax.swing.JLabel();
        lblPhoneValue = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        lblEditNote = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator(javax.swing.SwingConstants.VERTICAL);
        lblSupNameValue = new javax.swing.JLabel();
        lblSupEmail = new javax.swing.JLabel();
        lblSupPhone = new javax.swing.JLabel();
        lblSupExp = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblCountryName = new javax.swing.JLabel();
        lblCurrency = new javax.swing.JLabel();
        lblLanguage = new javax.swing.JLabel();
        lblContinent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 145702 (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Profile");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 150809.png"))); // NOI18N
        jButton1.setText("Edit Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 151249.png"))); // NOI18N
        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073823.png"))); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblHajjiIdValue.setBackground(new java.awt.Color(255, 255, 0));
        lblHajjiIdValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHajjiIdValue.setForeground(new java.awt.Color(255, 255, 0));
        lblHajjiIdValue.setText("Hajji_id:---");

        lblFirstNameValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFirstNameValue.setForeground(new java.awt.Color(255, 255, 0));
        lblFirstNameValue.setText("First Name:---");

        lblLastNameValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLastNameValue.setForeground(new java.awt.Color(255, 255, 0));
        lblLastNameValue.setText("Last Name:---");

        lblGenderValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGenderValue.setForeground(new java.awt.Color(255, 255, 0));
        lblGenderValue.setText("Gender:---");

        lblDobValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDobValue.setForeground(new java.awt.Color(255, 255, 0));
        lblDobValue.setText("Date of Birth:---");

        lblPhoneValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhoneValue.setForeground(new java.awt.Color(255, 255, 0));
        lblPhoneValue.setText("Phone:---");

        lblStatusValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblStatusValue.setForeground(new java.awt.Color(255, 255, 0));
        lblStatusValue.setText("Status:---");

        lblEditNote.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lblEditNote.setForeground(new java.awt.Color(102, 255, 102));
        lblEditNote.setText("You can only edit Phone and Password");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblSupNameValue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSupNameValue.setForeground(new java.awt.Color(255, 255, 0));
        lblSupNameValue.setText("Supervisor Name:---");

        lblSupEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSupEmail.setForeground(new java.awt.Color(255, 255, 0));
        lblSupEmail.setText("Email:---");

        lblSupPhone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSupPhone.setForeground(new java.awt.Color(255, 255, 0));
        lblSupPhone.setText("Phone:---");

        lblSupExp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSupExp.setForeground(new java.awt.Color(255, 255, 0));
        lblSupExp.setText("Experience Years:--");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCountryName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCountryName.setForeground(new java.awt.Color(255, 255, 0));
        lblCountryName.setText("Country Name:---");

        lblCurrency.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCurrency.setForeground(new java.awt.Color(255, 255, 0));
        lblCurrency.setText("Currency:---");

        lblLanguage.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLanguage.setForeground(new java.awt.Color(255, 255, 0));
        lblLanguage.setText("Language:---");

        lblContinent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblContinent.setForeground(new java.awt.Color(255, 255, 0));
        lblContinent.setText("Continent:---");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hajji Information");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supervisor Information");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Country Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(463, 463, 463)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(466, 466, 466)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditNote)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel3))
                                    .addComponent(lblHajjiIdValue)
                                    .addComponent(lblFirstNameValue)
                                    .addComponent(lblLastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGenderValue)
                                    .addComponent(lblDobValue)
                                    .addComponent(lblPhoneValue)
                                    .addComponent(lblStatusValue))
                                .addGap(118, 118, 118)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSupEmail)
                                            .addComponent(lblSupNameValue)
                                            .addComponent(lblSupPhone)
                                            .addComponent(lblSupExp)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel4)))
                                .addGap(93, 93, 93)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCountryName)
                                                    .addComponent(lblCurrency)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(lblLanguage)))
                                                .addGap(184, 184, 184)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(20, 20, 20)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblContinent)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel5)))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(6, 6, 6)
                        .addComponent(jButton3)))
                .addGap(6, 6, 6)
                .addComponent(lblEditNote)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblSupNameValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSupEmail)
                        .addGap(4, 4, 4)
                        .addComponent(lblSupPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSupExp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountryName)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLanguage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContinent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblHajjiIdValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFirstNameValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastNameValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGenderValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDobValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneValue)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusValue)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String currentPhone = lblPhoneValue.getText();

    // (2) نفتح Dialog يطلب رقم جديد
    JTextField txt = new JTextField(currentPhone);

    int opt = JOptionPane.showConfirmDialog(
        this,
        txt,
        "Edit Phone",
        JOptionPane.OK_CANCEL_OPTION
    );

    if (opt != JOptionPane.OK_OPTION) return;

    String newPhone = txt.getText().trim();
    if (newPhone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phone cannot be empty");
        return;
    }

    // (3) Update DB
    try {
        String sql = "UPDATE hajji_applicants SET phone=? WHERE hajji_id=?";
        pst = con.prepareStatement(sql);
        pst.setString(1, newPhone);
        pst.setInt(2, loggedHajjiId);

        int updated = pst.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Phone updated successfully!");
            loadProfile(); // تحديث اللّيبلات
        } else {
            JOptionPane.showMessageDialog(this, "No update happened!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update Phone Error: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JPasswordField oldPass = new JPasswordField();
    JPasswordField newPass = new JPasswordField();
    JPasswordField confirm = new JPasswordField();

    Object[] fields = {
        "Old Password:", oldPass,
        "New Password:", newPass,
        "Confirm New Password:", confirm
    };

    int opt = JOptionPane.showConfirmDialog(
        this,
        fields,
        "Change Password",
        JOptionPane.OK_CANCEL_OPTION
    );

    if (opt != JOptionPane.OK_OPTION) return;

    String oldP = new String(oldPass.getPassword()).trim();
    String newP = new String(newPass.getPassword()).trim();
    String conP = new String(confirm.getPassword()).trim();

    if (oldP.isEmpty() || newP.isEmpty() || conP.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All password fields are required");
        return;
    }
    if (!newP.equals(conP)) {
        JOptionPane.showMessageDialog(this, "New Password and Confirm do not match");
        return;
    }
    if (newP.length() < 6) {
        JOptionPane.showMessageDialog(this, "Password must be at least 6 characters");
        return;
    }
try {
    // تحقق من كلمة السر القديمة
    String checkSql =
        "SELECT 1 FROM users u " +
        "JOIN hajji_applicants h ON h.user_id = u.id " +
        "WHERE h.hajji_id = ? AND u.password = ?";

    pst = con.prepareStatement(checkSql);
    pst.setInt(1, loggedHajjiId);
    pst.setString(2, oldP);
    rs = pst.executeQuery();

    if (!rs.next()) {
        JOptionPane.showMessageDialog(this, "Old password is incorrect");
        return;
    }

    // تحديث كلمة السر
    String updateSql =
        "UPDATE users SET password = ? " +
        "WHERE id = (SELECT user_id FROM hajji_applicants WHERE hajji_id = ?)";

    pst = con.prepareStatement(updateSql);
    pst.setString(1, newP);
    pst.setInt(2, loggedHajjiId);
    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Password changed successfully!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Change Password Error: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int x = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblContinent;
    private javax.swing.JLabel lblCountryName;
    private javax.swing.JLabel lblCurrency;
    private javax.swing.JLabel lblDobValue;
    private javax.swing.JLabel lblEditNote;
    private javax.swing.JLabel lblFirstNameValue;
    private javax.swing.JLabel lblGenderValue;
    private javax.swing.JLabel lblHajjiIdValue;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblLastNameValue;
    private javax.swing.JLabel lblPhoneValue;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JLabel lblSupEmail;
    private javax.swing.JLabel lblSupExp;
    private javax.swing.JLabel lblSupNameValue;
    private javax.swing.JLabel lblSupPhone;
    // End of variables declaration//GEN-END:variables

    private void loadProfile() {
        try {
        String sql =
            "SELECT h.hajji_id, h.first_name, h.last_name, h.gender, h.dob, h.phone, h.status, " +
    "s.name AS sup_name, s.email AS sup_email, s.phone AS sup_phone, s.experience_years, " +
    "c.country_name, c.currency, c.language, c.continent " +
    "FROM hajji_applicants h " +
    "LEFT JOIN supervisor s ON h.supervisor_id = s.supervisor_id " +
    "LEFT JOIN country c ON h.country_id = c.country_id " +
    "WHERE h.hajji_id = ?";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedHajjiId);
        rs = pst.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this,
                "No Hajj profile found for this user");
            return;
        }

        lblHajjiIdValue.setText(String.valueOf(rs.getInt("hajji_id")));
        lblFirstNameValue.setText(rs.getString("first_name"));
        lblLastNameValue.setText(rs.getString("last_name"));
        lblGenderValue.setText(rs.getString("gender"));
        lblDobValue.setText(String.valueOf(rs.getDate("dob")));
        lblPhoneValue.setText(rs.getString("phone"));
        lblStatusValue.setText(rs.getString("status"));

        // بما إن ما عندك Supervisor / Country
        lblSupNameValue.setText("---");
        lblSupEmail.setText("---");
        lblSupPhone.setText("---");
        lblSupExp.setText("---");

        lblCountryName.setText("---");
        lblCurrency.setText("---");
        lblLanguage.setText("---");
        lblContinent.setText("---");
        // Supervisor
lblSupNameValue.setText(rs.getString("sup_name"));
lblSupEmail.setText(rs.getString("sup_email"));
lblSupPhone.setText(rs.getString("sup_phone"));
lblSupExp.setText(String.valueOf(rs.getInt("experience_years")));

// Country
lblCountryName.setText(rs.getString("country_name"));
lblCurrency.setText(rs.getString("currency"));
lblLanguage.setText(rs.getString("language"));
lblContinent.setText(rs.getString("continent"));


    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Load Profile Error: " + e.getMessage());
    }
    }
}
