import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class CustomerBookingPanel extends javax.swing.JPanel {
private int loggedHajjiId;
private Connection con;
    /**
     * Creates new form CustomerBookingPanel
     */
   public CustomerBookingPanel(int hajjiId) {
    initComponents();
        UITheme.applyPanel(this);
    this.loggedHajjiId = hajjiId;
    con = DBConnection.connect();
    loadMyBookings();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshBookings = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyBookings = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnCancelBooking = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 071027 (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Booking");

        btnRefreshBookings.setBackground(new java.awt.Color(255, 255, 0));
        btnRefreshBookings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRefreshBookings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073547 (1).png"))); // NOI18N
        btnRefreshBookings.setText("Refresh");
        btnRefreshBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshBookingsActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 061510.png"))); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblMyBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Package Name", "Start Date", "End Date", "Status", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(tblMyBookings);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Information");

        btnCancelBooking.setBackground(new java.awt.Color(255, 255, 0));
        btnCancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 072545.png"))); // NOI18N
        btnCancelBooking.setText("Cancel Booking");
        btnCancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 315, Short.MAX_VALUE)
                                .addComponent(btnRefreshBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelBooking)
                                .addGap(360, 360, 360))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(383, 383, 383)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(411, 411, 411)
                                        .addComponent(jButton2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(447, 447, 447))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefreshBookings))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookingActionPerformed
int row = tblMyBookings.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a booking first");
        return;
    }

    String status = tblMyBookings.getValueAt(row, 4).toString();
    if (status.equalsIgnoreCase("approved")) {
        JOptionPane.showMessageDialog(this,
            "Approved booking cannot be cancelled");
        return;
    }

    int bookingId = Integer.parseInt(
        tblMyBookings.getValueAt(row, 0).toString()
    );

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to cancel this booking?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        String sql =
            "UPDATE bookings SET status='cancelled' WHERE booking_id=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, bookingId);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
            "Booking cancelled successfully");
        loadMyBookings();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Cancel Error: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelBookingActionPerformed

    private void btnRefreshBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshBookingsActionPerformed
loadMyBookings();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshBookingsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int x = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

private void loadMyBookings() {
    try {
        DefaultTableModel model = (DefaultTableModel) tblMyBookings.getModel();
        model.setRowCount(0);

        String sql =
            "SELECT b.booking_id, p.package_name, p.start_date, p.end_date, " +
            "b.status, b.total_price " +
            "FROM bookings b " +
            "JOIN packages p ON b.package_id = p.package_id " +
            "WHERE b.hajji_id = ? " +
            "ORDER BY b.booking_id";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, loggedHajjiId);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("booking_id"),
                rs.getString("package_name"),
                rs.getDate("start_date"),
                rs.getDate("end_date"),
                rs.getString("status"),
                rs.getBigDecimal("total_price")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Load Booking Error: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelBooking;
    private javax.swing.JButton btnRefreshBookings;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyBookings;
    // End of variables declaration//GEN-END:variables
}
