import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class HotelPanel extends javax.swing.JPanel {
private int loggedHajjiId;
    private Connection con;

    public HotelPanel(int hajjiId) {
        initComponents();
        UITheme.applyPanel(this);
        this.loggedHajjiId = hajjiId;
        con = DBConnection.connect();
        loadMyHotels();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyHotels = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRefreshHotel = new javax.swing.JButton();
        btnCancelHotel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 123336.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MyHotel");

        tblMyHotels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Hotel ID", "Hotel Name", "City", "Room Type", "Check-in Date", "Check-out Date", "Stateus", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblMyHotels);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Information");

        btnRefreshHotel.setBackground(new java.awt.Color(255, 255, 0));
        btnRefreshHotel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRefreshHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073547 (1).png"))); // NOI18N
        btnRefreshHotel.setText("Refresh");
        btnRefreshHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshHotelActionPerformed(evt);
            }
        });

        btnCancelHotel.setBackground(new java.awt.Color(255, 255, 0));
        btnCancelHotel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 072545.png"))); // NOI18N
        btnCancelHotel.setText("Cancel Hotel");
        btnCancelHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelHotelActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 061510.png"))); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRefreshHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelHotel)
                                .addGap(413, 413, 413))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(542, 542, 542))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(492, 492, 492))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefreshHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshHotelActionPerformed
loadMyHotels();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshHotelActionPerformed

    private void btnCancelHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelHotelActionPerformed
int row = tblMyHotels.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a hotel booking first");
            return;
        }

        String status = tblMyHotels.getValueAt(row, 6).toString();
        if (status.equalsIgnoreCase("approved")) {
            JOptionPane.showMessageDialog(this,
                "Approved booking cannot be cancelled");
            return;
        }

        int bookingId =
            Integer.parseInt(tblMyHotels.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to cancel this hotel booking?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            String sql =
                "UPDATE hotel_bookings SET status='cancelled' WHERE booking_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookingId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Hotel booking cancelled successfully");
            loadMyHotels();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Cancel Error: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelHotelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int x = JOptionPane.showConfirmDialog(
        this,
        "Do you want to logout?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );

    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        javax.swing.SwingUtilities
            .getWindowAncestor(this)
            .dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelHotel;
    private javax.swing.JButton btnRefreshHotel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyHotels;
    // End of variables declaration//GEN-END:variables

    private void loadMyHotels() {
        try {
            DefaultTableModel model =
                (DefaultTableModel) tblMyHotels.getModel();
            model.setRowCount(0);

            String sql =
                "SELECT hb.booking_id, h.hotel_name, h.city, " +
                "hb.room_type, hb.check_in, hb.check_out, " +
                "hb.status, hb.price " +
                "FROM hotel_bookings hb " +
                "JOIN hotels h ON hb.hotel_id = h.hotel_id " +
                "WHERE hb.hajji_id = ? " +
                "ORDER BY hb.booking_id";

            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, loggedHajjiId);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("booking_id"),
                    rs.getString("hotel_name"),
                    rs.getString("city"),
                    rs.getString("room_type"),
                    rs.getDate("check_in"),
                    rs.getDate("check_out"),
                    rs.getString("status"),
                    rs.getBigDecimal("price")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Load Hotel Error: " + e.getMessage());
        }
    
    }
}
