import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class MessagesPanel extends javax.swing.JPanel {
 private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

    private int loggedEmpId;
    /**
     * Creates new form MessagesPanel
     */
   public MessagesPanel(int empId) {
      initComponents();
        UITheme.applyPanel(this);

    this.loggedEmpId = empId;
    con = DBConnection.connect();

    loadMessages();
    loadUnreadCounter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnMarkRead = new javax.swing.JButton();
        btnReply = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblUnreadCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 044909.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Messages");

        btnRefresh.setBackground(new java.awt.Color(255, 255, 0));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073547 (1).png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnMarkRead.setBackground(new java.awt.Color(255, 255, 0));
        btnMarkRead.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMarkRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 045939.png"))); // NOI18N
        btnMarkRead.setText("MarkRead");
        btnMarkRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkReadActionPerformed(evt);
            }
        });

        btnReply.setBackground(new java.awt.Color(255, 255, 0));
        btnReply.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 050024.png"))); // NOI18N
        btnReply.setText("Reply");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073823.png"))); // NOI18N
        btnLogout.setText("btnLogout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUnreadCount.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lblUnreadCount.setForeground(new java.awt.Color(0, 255, 0));
        lblUnreadCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 050905.png"))); // NOI18N
        lblUnreadCount.setText("UnreadMessages:0");

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message ID ", "Sender", "Message ", "Date ", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblMessages);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUnreadCount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLogout)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRefresh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMarkRead)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReply))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel3)))))
                .addGap(0, 307, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblUnreadCount))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnMarkRead)
                            .addComponent(btnReply, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarkReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkReadActionPerformed
int row = tblMessages.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a message first");
        return;
    }

    int msgId = Integer.parseInt(tblMessages.getValueAt(row, 0).toString());

    try {
        String sql =
           "UPDATE employee_Messagess SET status='Read' " +
    "WHERE message_id=? AND emp_id=?";

        pst = con.prepareStatement(sql);
        pst.setInt(1, msgId);
        pst.setInt(2, loggedEmpId);
        pst.executeUpdate();

        loadMessages();
        loadUnreadCounter();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarkReadActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
loadMessages();
    loadUnreadCounter();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
int row = tblMessages.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a message first");
        return;
    }

    JTextArea txtReply = new JTextArea(5, 30);
    txtReply.setLineWrap(true);
    txtReply.setWrapStyleWord(true);

    int option = JOptionPane.showConfirmDialog(
        this,
        new JScrollPane(txtReply),
        "Reply Message",
        JOptionPane.OK_CANCEL_OPTION
    );

    if (option == JOptionPane.OK_OPTION) {
        String reply = txtReply.getText().trim();

        if (reply.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Reply cannot be empty");
            return;
        }

        try {
            String sql =
                "INSERT INTO employee_messages (emp_id, sender, message, status) " +
                "VALUES (?, 'Employee', ?, 'Unread')";

            pst = con.prepareStatement(sql);
            pst.setInt(1, loggedEmpId);
            pst.setString(2, reply);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Reply sent successfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Reply Error: " + e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnReplyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int x = JOptionPane.showConfirmDialog(
        this,
        "Do you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);   // غيّر الاسم حسب الفورم عندك
        SwingUtilities.getWindowAncestor(this).dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarkRead;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUnreadCount;
    private javax.swing.JTable tblMessages;
    // End of variables declaration//GEN-END:variables

    private void loadMessages() {
      try {
        String sql =
            "SELECT message_id, sender, message, sent_at, status " +
    "FROM employee_Messagess " +
    "WHERE emp_id=? " +
    "ORDER BY sent_at DESC";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedEmpId);
        rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblMessages.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("message_id"),
                rs.getString("sender"),
                rs.getString("message"),
                rs.getTimestamp("sent_at"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Load Messages Error: " + e.getMessage());
    }
    }

    private void loadUnreadCounter() {
        try {
        String sql =
    "SELECT COUNT(*) FROM employee_Messagess " +
    "WHERE emp_id=? AND status='Unread'";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedEmpId);
        rs = pst.executeQuery();

        if (rs.next()) {
            lblUnreadCount.setText("Unread Messages: " + rs.getInt(1));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Counter Error: " + e.getMessage());
    }
    }
}
