import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class MyTasksPanel extends javax.swing.JPanel {
     private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private javax.swing.JLabel lblPendingCount;
private javax.swing.JLabel lblDoneCount;

    private int loggedEmpId;

    /**
     * Creates new form MyTasksPanel
     */
  public MyTasksPanel(int empId) {
    initComponents();
        UITheme.applyPanel(this);

    this.loggedEmpId = empId;        // 1️⃣ أول شي
    con = DBConnection.connect();    // 2️⃣ ثاني شي

    setupTableClick();
    loadTasks();
    loadTaskCounters();  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        btnMarkDone = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblPending = new javax.swing.JLabel();
        lblDone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 013950.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Tasks");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Employee can only view and update task status");

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task ID", "Title", "Description", "Status", "Due Date"
            }
        ));
        jScrollPane1.setViewportView(tblTasks);

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Done" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 255, 0));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073547.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnMarkDone.setBackground(new java.awt.Color(255, 255, 0));
        btnMarkDone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarkDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 024804.png"))); // NOI18N
        btnMarkDone.setText("Mark as Done");
        btnMarkDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkDoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("My Information");

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 061510.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblPending.setBackground(new java.awt.Color(255, 51, 51));
        lblPending.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPending.setForeground(new java.awt.Color(255, 51, 51));
        lblPending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 042843.png"))); // NOI18N
        lblPending.setText("Pending Tasks:0");

        lblDone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDone.setForeground(new java.awt.Color(51, 255, 0));
        lblDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-19 042722.png"))); // NOI18N
        lblDone.setText("Done Tasks: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(308, 308, 308)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(lblDone)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMarkDone))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addComponent(btnLogout))))
                    .addComponent(jLabel3))
                .addGap(159, 159, 159)
                .addComponent(lblPending)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPending)
                            .addComponent(lblDone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnMarkDone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnMarkDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkDoneActionPerformed
        int row = tblTasks.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a task first.");
        return;
    }

    int taskId = Integer.parseInt(tblTasks.getValueAt(row, 0).toString());

    try {
        String sql = "UPDATE employee_tasks SET status='Done' WHERE task_id=? AND emp_id=?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, taskId);
        pst.setInt(2, loggedEmpId);

        int updated = pst.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Task marked as Done!");
            loadTasks();
        } else {
            JOptionPane.showMessageDialog(this, "No task updated (check task belongs to you).");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
    }
loadTasks();
loadTaskCounters();// TODO add your handling code here:
    }//GEN-LAST:event_btnMarkDoneActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    
loadTasks();
loadTaskCounters();// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int x = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true); // غيّرها لاسم اللوجين عندك
        SwingUtilities.getWindowAncestor(this).dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarkDone;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDone;
    private javax.swing.JLabel lblPending;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables

    private void setupTableClick() {
         tblTasks.getSelectionModel().addListSelectionListener(e -> {
        int row = tblTasks.getSelectedRow();
        if (row != -1) {
            String status = tblTasks.getValueAt(row, 3).toString();
            cmbStatus.setSelectedItem(status);
        }
    });
    }

    private void loadTasks() {
        try {
        String sql =
            "SELECT task_id, title, description, status, due_date " +
            "FROM employee_tasks " +
            "WHERE emp_id = ? " +
            "ORDER BY due_date";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedEmpId);
        rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("task_id"),
                rs.getString("title"),
                rs.getString("description"),
                rs.getString("status"),
                rs.getDate("due_date")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Load Tasks Error: " + e.getMessage());
    }
    }

 private void loadTaskCounters() {
    try {
        String sql =
            "SELECT " +
            "SUM(CASE WHEN status = 'Pending' THEN 1 ELSE 0 END) AS pending_count, " +
            "SUM(CASE WHEN status = 'Done' THEN 1 ELSE 0 END) AS done_count " +
            "FROM employee_tasks WHERE emp_id = ?";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedEmpId);
        rs = pst.executeQuery();

        if (rs.next()) {
            lblPending.setText("Pending Tasks: " + rs.getInt("pending_count"));
            lblDone.setText("Done Tasks: " + rs.getInt("done_count"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Counter Error: " + e.getMessage());
    }
}
}
