import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Transport extends javax.swing.JPanel {
private Connection con;
private PreparedStatement pst;
private ResultSet rs;
private int loggedHajjiId;
    /**
     * Creates new form Transport
     */
    public Transport(int hajjiId) {
    initComponents();
        UITheme.applyPanel(this);
    this.loggedHajjiId = hajjiId;
    con = DBConnection.connect();
    loadMyTransport();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyTransport = new javax.swing.JTable();
        btnRefreshTransport = new javax.swing.JButton();
        btnCancelTransport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Transport");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 114015.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        tblMyTransport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Transport ID", "Company Name ", "Vehicle Type ", "From Location ", "To Location ", "Departure Date ", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblMyTransport);

        btnRefreshTransport.setBackground(new java.awt.Color(255, 255, 0));
        btnRefreshTransport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnRefreshTransport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 073547 (1).png"))); // NOI18N
        btnRefreshTransport.setText("Refresh");
        btnRefreshTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTransportActionPerformed(evt);
            }
        });

        btnCancelTransport.setBackground(new java.awt.Color(255, 255, 0));
        btnCancelTransport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelTransport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-20 072545.png"))); // NOI18N
        btnCancelTransport.setText("Cancel Transport");
        btnCancelTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTransportActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-18 061510.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(403, 403, 403)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(btnRefreshTransport, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelTransport)))
                        .addGap(0, 372, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(btnLogout)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(473, 473, 473))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefreshTransport)
                            .addComponent(btnCancelTransport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTransportActionPerformed
loadMyTransport();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshTransportActionPerformed

    private void btnCancelTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTransportActionPerformed
int row = tblMyTransport.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a transport first");
        return;
    }

    String status = tblMyTransport.getValueAt(row, 6).toString();
    if (status.equalsIgnoreCase("approved")) {
        JOptionPane.showMessageDialog(this,
            "Approved transport cannot be cancelled");
        return;
    }

    int transportId = Integer.parseInt(
        tblMyTransport.getValueAt(row, 0).toString()
    );

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to cancel this transport?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        String sql =
            "UPDATE hajji_transports SET status='cancelled' " +
            "WHERE hajji_id=? AND transport_id=?";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedHajjiId);
        pst.setInt(2, transportId);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
            "Transport cancelled successfully");
        loadMyTransport();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Cancel Error: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelTransportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int x = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (x == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }          // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelTransport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshTransport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyTransport;
    // End of variables declaration//GEN-END:variables

    private void loadMyTransport() {
         try {
        DefaultTableModel model =
            (DefaultTableModel) tblMyTransport.getModel();
        model.setRowCount(0);

        String sql =
            "SELECT t.transport_id, c.company_name, t.vehicle_type, " +
            "t.from_location, t.to_location, t.departure_date, ht.status " +
            "FROM hajji_transports ht " +
            "JOIN transports t ON ht.transport_id = t.transport_id " +
            "JOIN transport_companies c ON t.company_id = c.company_id " +
            "WHERE ht.hajji_id = ? " +
            "ORDER BY t.departure_date";

        pst = con.prepareStatement(sql);
        pst.setInt(1, loggedHajjiId);
        rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getInt("transport_id"),
                rs.getString("company_name"),
                rs.getString("vehicle_type"),
                rs.getString("from_location"),
                rs.getString("to_location"),
                rs.getDate("departure_date"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Load Transport Error: " + e.getMessage());
    }
    }
}
